/**
 * Manual Oficial CME Group: 25 Estratégias Comprovadas para Negociar Opções
 * Adaptado para Ações e Derivativos da B3 com Strikes Reais
 */

export interface CMEStrategySpec {
  id: number;
  name: string;
  originalName: string;
  category: 'Direcional' | 'Precisão' | 'Arbitragem';
  bias: 'ALTA' | 'BAIXA' | 'LATERAL' | 'VOLATILIDADE' | 'NEUTRO';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  legsDescription: string;
  synthetics?: string;
  whenToUse: string;
  profitProfile: string;
  lossProfile: string;
  timeDecayProfile: string;
  payoffShape: 'line_up' | 'line_down' | 'trava_alta' | 'trava_baixa' | 'borboleta' | 'straddle_v' | 'straddle_inv' | 'strangle_u' | 'strangle_inv' | 'backspread_up' | 'backspread_down' | 'box';
}

export const CME_25_STRATEGIES: CMEStrategySpec[] = [
  {
    id: 1,
    name: 'Posição Comprada em Ações / Futuros',
    originalName: 'Long Futures / Long Stock',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Compra direta do ativo-objeto no mercado à vista.',
    synthetics: 'Posição comprada em Call A e vendida em Put A.',
    whenToUse: 'Quando você está otimista com as perspectivas do mercado e busca retorno direto na valorização do ativo.',
    profitProfile: 'O lucro aumenta linearmente à medida que o preço da ação sobe acima do preço de entrada.',
    lossProfile: 'O prejuízo aumenta linearmente à medida que a ação cai abaixo do ponto de entrada (protegido por Stop Loss).',
    timeDecayProfile: 'Nenhuma depreciação temporal direta (Theta = 0).',
    payoffShape: 'line_up',
  },
  {
    id: 2,
    name: 'Posição Vendida em Ações / Futuros',
    originalName: 'Short Futures / Short Stock',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Iniciante',
    legsDescription: 'Venda a descoberto (aluguel) ou saída total de posição.',
    synthetics: 'Posição comprada em Put A e vendida em Call A.',
    whenToUse: 'Quando você está pessimista com as perspectivas do mercado ou acionou stop loss técnico.',
    profitProfile: 'O lucro aumenta à medida que o preço do mercado cai em relação à entrada.',
    lossProfile: 'O prejuízo aumenta se o ativo subir acima do ponto de venda.',
    timeDecayProfile: 'Nenhuma depreciação temporal direta.',
    payoffShape: 'line_down',
  },
  {
    id: 3,
    name: 'Posição Comprada Sintética',
    originalName: 'Long Synthetic Futures',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Call no Strike A e Vender Put no Strike A (mesmo vencimento e strike).',
    synthetics: 'Equivalente sintético a comprar a ação no mercado à vista com alavancagem.',
    whenToUse: 'Quando você está muito otimista e deseja replicar a compra da ação com baixo desembolso de capital.',
    profitProfile: 'Lucro ilimitado para cima acima do strike A.',
    lossProfile: 'Prejuízo ilimitado para baixo caso o mercado caia abaixo do strike A.',
    timeDecayProfile: 'Neutro (o decaimento da Call comprada é compensado pelo decaimento da Put vendida).',
    payoffShape: 'line_up',
  },
  {
    id: 4,
    name: 'Posição Vendida Sintética',
    originalName: 'Short Synthetic Futures',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Put no Strike A e Vender Call no Strike A.',
    synthetics: 'Equivalente sintético a vender a ação a descoberto.',
    whenToUse: 'Quando você está pessimista e quer lucrar com a queda sem alugar o ativo à vista.',
    profitProfile: 'Lucro aumenta à medida que o mercado cai abaixo do strike A.',
    lossProfile: 'Prejuízo em aberto se o mercado subir acima do strike A.',
    timeDecayProfile: 'Neutro.',
    payoffShape: 'line_down',
  },
  {
    id: 5,
    name: 'Long Risk Reversal (Túnel Comprado)',
    originalName: 'Long Risk Reversal (Split Strike)',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Call no Strike B (OTM) e Vender Put no Strike A (OTM abaixo).',
    whenToUse: 'Quando você está otimista e quer financiar a compra de uma Call com a venda de uma Put fora do dinheiro.',
    profitProfile: 'Lucro expressivo se o mercado subir acima do strike B.',
    lossProfile: 'Prejuízo se o mercado desabar abaixo do strike A da Put vendida.',
    timeDecayProfile: 'Varia conforme a proximidade do vencimento e distância dos strikes.',
    payoffShape: 'line_up',
  },
  {
    id: 6,
    name: 'Short Risk Reversal (Túnel Vendido)',
    originalName: 'Short Risk Reversal (Split Strike)',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Put no Strike A (OTM) e Vender Call no Strike B (OTM acima).',
    whenToUse: 'Quando você está pessimista e financia a compra de Put com a venda de Call fora do dinheiro.',
    profitProfile: 'Lucro na queda abaixo do strike A.',
    lossProfile: 'Prejuízo se o mercado disparar acima do strike B.',
    timeDecayProfile: 'Depende da relação de prêmios.',
    payoffShape: 'line_down',
  },
  {
    id: 7,
    name: 'Compra a Seco de Call',
    originalName: 'Long Call',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Call no Strike A (ATM ou OTM).',
    synthetics: 'Comprar o ativo e comprar uma Put no Strike A.',
    whenToUse: 'Quando você está muito otimista com expectativas de alta rápida e quer arriscar apenas o prêmio pago.',
    profitProfile: 'Lucro ilimitado à medida que a ação sobe. Ponto de equilíbrio = Strike A + Prêmio pago.',
    lossProfile: 'Prejuízo limitado estritamente ao prêmio pago pela opção.',
    timeDecayProfile: 'Sofre forte depreciação temporal com o passar dos dias (Theta negativo).',
    payoffShape: 'trava_alta',
  },
  {
    id: 8,
    name: 'Venda Coberta de Call',
    originalName: 'Short Call (Covered)',
    category: 'Direcional',
    bias: 'LATERAL',
    difficulty: 'Iniciante',
    legsDescription: 'Possuir o ativo à vista e Vender Call no Strike A (OTM).',
    whenToUse: 'Para gerar renda periódica sobre a carteira de ações quando o mercado estiver lateral ou levemente altista.',
    profitProfile: 'Lucro limitado ao prêmio recebido + valorização do ativo até o strike A.',
    lossProfile: 'O risco é a queda do ativo à vista (a Call vendida ameniza as perdas pelo valor do prêmio).',
    timeDecayProfile: 'Altamente beneficiada pela depreciação do tempo (Theta positivo a favor).',
    payoffShape: 'trava_alta',
  },
  {
    id: 9,
    name: 'Compra a Seco de Put',
    originalName: 'Long Put (Hedge)',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Put no Strike A.',
    synthetics: 'Vender o ativo e comprar uma Call no Strike A.',
    whenToUse: 'Quando você está pessimista ou quer proteger uma carteira de ações contra quedas abruptas (Seguro).',
    profitProfile: 'Lucro expressivo conforme a ação cai. Ponto de equilíbrio = Strike A - Prêmio pago.',
    lossProfile: 'Prejuízo limitado estritamente ao prêmio investido na Put.',
    timeDecayProfile: 'Sofre com a depreciação do tempo.',
    payoffShape: 'trava_baixa',
  },
  {
    id: 10,
    name: 'Venda de Put para Aquisição / Renda',
    originalName: 'Short Put',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Intermediário',
    legsDescription: 'Vender Put no Strike A (OTM) garantindo margem em dinheiro.',
    whenToUse: 'Quando você acredita que o mercado não vai cair e quer comprar a ação com desconto ou embolsar o prêmio.',
    profitProfile: 'Lucro limitado ao prêmio recebido com a venda da opção.',
    lossProfile: 'Obrigação de comprar o ativo no strike A caso o mercado caia.',
    timeDecayProfile: 'Beneficiada pela perda de valor de tempo.',
    payoffShape: 'trava_alta',
  },
  {
    id: 11,
    name: 'Trava de Alta (Bull Spread)',
    originalName: 'Bull Spread (Call/Put)',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Call Strike A e Vender Call Strike B (ou Vender Put Strike B e Comprar Put Strike A a crédito).',
    whenToUse: 'A estratégia altista mais popular. Ideal para altas moderadas com risco e custo reduzidos.',
    profitProfile: 'Lucro máximo no strike B menos o custo inicial (ou crédito recebido).',
    lossProfile: 'Prejuízo máximo estritamente limitado à diferença do spread ou custo líquido pago.',
    timeDecayProfile: 'Equilibrado. Beneficia-se do tempo se o preço estiver próximo do strike B.',
    payoffShape: 'trava_alta',
  },
  {
    id: 12,
    name: 'Trava de Baixa (Bear Spread)',
    originalName: 'Bear Spread (Put/Call)',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Put Strike B e Vender Put Strike A (ou Vender Call Strike A e Comprar Call Strike B a crédito).',
    whenToUse: 'A estratégia baixista mais popular. Lucra com a queda moderada do ativo com risco travado.',
    profitProfile: 'Lucro máximo no strike A.',
    lossProfile: 'Prejuízo limitado ao custo líquido do spread.',
    timeDecayProfile: 'Beneficiada pelo tempo se o mercado estiver abaixo do strike A.',
    payoffShape: 'trava_baixa',
  },
  {
    id: 13,
    name: 'Borboleta Comprada (Long Butterfly)',
    originalName: 'Long Butterfly',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Call A, Vender 2 Calls B (miolo) e Comprar 1 Call C (asas simétricas).',
    whenToUse: 'Quando você prevê que o ativo ficará exatamente no strike central B no vencimento (mercado estável).',
    profitProfile: 'Lucro máximo cravado no strike central B com excelente relação Risco:Retorno (até 1:5).',
    lossProfile: 'Perda máxima limitada ao custo irrisório pago pelo spread.',
    timeDecayProfile: 'Gera aceleração exponencial de lucro no último mês se estiver perto de B.',
    payoffShape: 'borboleta',
  },
  {
    id: 14,
    name: 'Borboleta Vendida (Short Butterfly)',
    originalName: 'Short Butterfly',
    category: 'Precisão',
    bias: 'VOLATILIDADE',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call A, Comprar 2 Calls B e Vender 1 Call C.',
    whenToUse: 'Quando o mercado está no strike B e você espera um movimento forte para qualquer um dos lados.',
    profitProfile: 'Lucro equivalente ao crédito líquido se o mercado romper abaixo de A ou acima de C.',
    lossProfile: 'Prejuízo máximo ocorre se o mercado parar exatamente no strike B.',
    timeDecayProfile: 'Desfavorável se o mercado continuar estático em B.',
    payoffShape: 'straddle_inv',
  },
  {
    id: 15,
    name: 'Long Iron Butterfly',
    originalName: 'Long Iron Butterfly',
    category: 'Precisão',
    bias: 'VOLATILIDADE',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Straddle no Strike B e Vender Strangle na faixa de A a C.',
    whenToUse: 'Quando você busca explosão direcional a partir de uma zona de consolidação com custo reduzido.',
    profitProfile: 'Lucro se o ativo romper a faixa de A ou C.',
    lossProfile: 'Prejuízo limitado ao débito inicial se ficar parado em B.',
    timeDecayProfile: 'Depreciação rápida no mês final.',
    payoffShape: 'strangle_u',
  },
  {
    id: 16,
    name: 'Short Iron Butterfly (Condor Central)',
    originalName: 'Short Iron Butterfly',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call e 1 Put no Strike B, Comprar 1 Put A e Comprar 1 Call C (para proteção total).',
    whenToUse: 'Recomendada para longos períodos de consolidação e lateralização, com crédito inicial elevado.',
    profitProfile: 'Lucro máximo no strike central B igual ao crédito líquido recebido.',
    lossProfile: 'Perda máxima estritamente limitada à largura da asa menos o crédito recebido.',
    timeDecayProfile: 'Máximo benefício com o decaimento do tempo (Theta positivo).',
    payoffShape: 'borboleta',
  },
  {
    id: 17,
    name: 'Straddle Comprado (Long Straddle)',
    originalName: 'Long Straddle',
    category: 'Precisão',
    bias: 'VOLATILIDADE',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Call Strike A + Comprar Put Strike A (mesmo strike e vencimento).',
    whenToUse: 'Antes de divulgações de resultados (balanço) ou eventos binários onde se espera forte erupção de preço.',
    profitProfile: 'Lucro ilimitado para ambos os lados se o ativo oscilar mais que o custo do prêmio total.',
    lossProfile: 'Prejuízo máximo limitado ao custo do spread se o preço ficar parado em A.',
    timeDecayProfile: 'Forte perda diária de valor de tempo se o mercado não se mover rapidamente.',
    payoffShape: 'straddle_v',
  },
  {
    id: 18,
    name: 'Straddle Vendido (Short Straddle)',
    originalName: 'Short Straddle',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Vender Call Strike A + Vender Put Strike A.',
    whenToUse: 'Quando a volatilidade implícita está muito alta e o mercado deve se estabilizar no strike A.',
    profitProfile: 'Lucro máximo no strike A igual aos dois prêmios recebidos.',
    lossProfile: 'Risco em aberto para ambos os lados.',
    timeDecayProfile: 'Decaimento temporal acelerado a favor do lançador.',
    payoffShape: 'straddle_inv',
  },
  {
    id: 19,
    name: 'Strangle Comprado (Long Strangle)',
    originalName: 'Long Strangle',
    category: 'Precisão',
    bias: 'VOLATILIDADE',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Put Strike A (OTM) e Comprar Call Strike B (OTM).',
    whenToUse: 'Para capturar grandes oscilações com custo menor do que o Straddle.',
    profitProfile: 'Lucro em aberto para ambos os lados fora da faixa A a B.',
    lossProfile: 'Perda limitada ao prêmio pago se ficar entre A e B.',
    timeDecayProfile: 'Depreciação contínua.',
    payoffShape: 'strangle_u',
  },
  {
    id: 20,
    name: 'Short Strangle Coberto (Iron Condor)',
    originalName: 'Covered Short Strangle / Iron Condor',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Put A (proteção queda), Vender Put B (suporte), Vender Call C (resistência) e Comprar Call D (proteção alta).',
    whenToUse: 'Quando a tendência é lateral, a empresa possui bons fundamentos e a volatilidade implícita está moderada a alta para coleta de crédito.',
    profitProfile: 'Lucro máximo igual ao crédito líquido recebido se o ativo expirar entre os strikes B e C.',
    lossProfile: 'Perda máxima 100% limitada à largura da asa menos o crédito recebido (sem risco de cauda).',
    timeDecayProfile: 'Máxima rentabilização diária via decaimento do tempo (Theta positivo) e contração de volatilidade.',
    payoffShape: 'strangle_inv',
  },
  {
    id: 21,
    name: 'Ratio Call Spread (Venda de Volatilidade Call)',
    originalName: 'Ratio Call Spread',
    category: 'Precisão',
    bias: 'ALTA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Call no Strike A e Vender 2 Calls no Strike B.',
    whenToUse: 'Quando você espera uma alta moderada até o strike B, mas quer zerar o custo da operação.',
    profitProfile: 'Lucro máximo cravado no strike B.',
    lossProfile: 'Risco em aberto se o ativo disparar muito acima de B.',
    timeDecayProfile: 'Positivo se o mercado estiver perto de B.',
    payoffShape: 'trava_alta',
  },
  {
    id: 22,
    name: 'Ratio Put Spread (Venda de Volatilidade Put)',
    originalName: 'Ratio Put Spread',
    category: 'Precisão',
    bias: 'BAIXA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Put no Strike B e Vender 2 Puts no Strike A.',
    whenToUse: 'Quando você espera uma queda moderada até o strike A sem custo de montagem.',
    profitProfile: 'Lucro máximo no strike A.',
    lossProfile: 'Risco de compra de ações se cair muito abaixo de A.',
    timeDecayProfile: 'Positivo perto de A.',
    payoffShape: 'trava_baixa',
  },
  {
    id: 23,
    name: 'Call Ratio Backspread (Compra de Volatilidade Call)',
    originalName: 'Call Ratio Backspread',
    category: 'Precisão',
    bias: 'ALTA',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call no Strike A e Comprar 2 Calls no Strike B (OTM).',
    whenToUse: 'Quando o mercado dá sinais de explosão altista violenta após consolidação.',
    profitProfile: 'Lucro ilimitado e acelerado na alta forte.',
    lossProfile: 'Prejuízo máximo limitado se o ativo parar exatamente no strike B.',
    timeDecayProfile: 'Beneficia-se da explosão de volatilidade.',
    payoffShape: 'backspread_up',
  },
  {
    id: 24,
    name: 'Put Ratio Backspread (Compra de Volatilidade Put)',
    originalName: 'Put Ratio Backspread',
    category: 'Precisão',
    bias: 'BAIXA',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Put no Strike B e Comprar 2 Puts no Strike A (OTM).',
    whenToUse: 'Quando se espera um crash ou queda vertiginosa do mercado com aumento de volatilidade.',
    profitProfile: 'Lucro exponencial na queda livre.',
    lossProfile: 'Prejuízo limitado se o ativo parar no strike A.',
    timeDecayProfile: 'Sensível ao aumento de IV.',
    payoffShape: 'backspread_down',
  },
  {
    id: 25,
    name: 'Box Spread (Operação Travada de Arbitragem)',
    originalName: 'Box Spread',
    category: 'Arbitragem',
    bias: 'NEUTRO',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Trava de Alta (Call A + Call B) e Comprar Trava de Baixa (Put B + Put A).',
    whenToUse: 'Operação sintética 100% travada usada para capturar distorções de taxa de juros ou fechar posições.',
    profitProfile: 'O valor no vencimento é exatamente constante (Strike B - Strike A) independente do preço do ativo.',
    lossProfile: 'Risco nulo no vencimento (retorno de renda fixa sintética).',
    timeDecayProfile: 'Neutro.',
    payoffShape: 'box',
  },
];

/**
 * Seleciona a estratégia CME ideal com base no Veredito CNPI e nas condições técnicas
 */
export function getRecommendedCMEStrategy(
  verdict: string,
  rsi: number | null,
  trend: string
): CMEStrategySpec {
  if (verdict.includes('COMPRA') || trend === 'ALTA') {
    if (rsi && rsi > 65) {
      // Mercado esticado em alta -> Bull Spread (Trava de alta com risco limitado)
      return CME_25_STRATEGIES[10]; // Bull Spread (#11)
    }
    return CME_25_STRATEGIES[10]; // Bull Spread (#11) ou Long Call (#7)
  }

  if (verdict.includes('VENDA') || trend === 'BAIXA') {
    return CME_25_STRATEGIES[11]; // Bear Spread (#12)
  }

  // Mercado Lateral / Consolidação
  return CME_25_STRATEGIES[15]; // Short Iron Butterfly (#16) ou Long Butterfly (#13)
}
