/**
 * Catálogo Oficial de 25 Estratégias Comprovadas de Opções
 * Adaptado para Ações e Derivativos da B3 com Strikes Reais
 */

export interface OptionStrategySpec {
  id: number;
  name: string;
  originalName: string;
  category: 'Direcional' | 'Precisão' | 'Arbitragem';
  bias: 'ALTA' | 'BAIXA' | 'LATERAL' | 'VOLATILIDADE' | 'NEUTRO';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  legsDescription: string;
  synthetics?: string;
  whenToUse: string;
  profitProfile: string;
  lossProfile: string;
  timeDecayProfile: string;
  payoffShape: 'line_up' | 'line_down' | 'trava_alta' | 'trava_baixa' | 'borboleta' | 'straddle_v' | 'straddle_inv' | 'strangle_u' | 'strangle_inv' | 'backspread_up' | 'backspread_down' | 'box';
}

export type CMEStrategySpec = OptionStrategySpec;

export const OPTION_25_STRATEGIES: OptionStrategySpec[] = [
  {
    id: 1,
    name: 'Posição Comprada em Ações',
    originalName: 'Long Stock',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Compra direta do ativo-objeto no mercado à vista.',
    synthetics: 'Posição comprada em Call A e vendida em Put A.',
    whenToUse: 'Quando você está otimista com as perspectivas do mercado e busca retorno direto na valorização do ativo.',
    profitProfile: 'O lucro aumenta linearmente à medida que o preço da ação sobe acima do preço de entrada.',
    lossProfile: 'O prejuízo aumenta linearmente à medida que a ação cai abaixo do ponto de entrada (protegido por Stop Loss).',
    timeDecayProfile: 'Nenhuma depreciação temporal direta (Theta = 0).',
    payoffShape: 'line_up',
  },
  {
    id: 2,
    name: 'Posição Vendida em Ações',
    originalName: 'Short Stock',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Iniciante',
    legsDescription: 'Venda a descoberto (aluguel) ou saída total de posição.',
    synthetics: 'Posição comprada em Put A e vendida em Call A.',
    whenToUse: 'Quando você está pessimista com as perspectivas do mercado ou acionou stop loss técnico.',
    profitProfile: 'O lucro aumenta à medida que o preço do mercado cai em relação à entrada.',
    lossProfile: 'O prejuízo aumenta se o ativo subir acima do ponto de venda.',
    timeDecayProfile: 'Nenhuma depreciação temporal direta.',
    payoffShape: 'line_down',
  },
  {
    id: 3,
    name: 'Posição Comprada Sintética',
    originalName: 'Long Synthetic Futures / Stock',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Call no Strike A e Vender Put no Strike A (mesmo vencimento e strike).',
    synthetics: 'Equivalente sintético a comprar a ação no mercado à vista com alavancagem.',
    whenToUse: 'Quando você está muito otimista e deseja replicar a compra da ação com baixo desembolso de capital.',
    profitProfile: 'Lucro ilimitado para cima acima do strike A.',
    lossProfile: 'Prejuízo ilimitado para baixo caso o mercado caia abaixo do strike A.',
    timeDecayProfile: 'Neutro (o decaimento da Call comprada é compensado pelo decaimento da Put vendida).',
    payoffShape: 'line_up',
  },
  {
    id: 4,
    name: 'Posição Vendida Sintética',
    originalName: 'Short Synthetic Futures / Stock',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Put no Strike A e Vender Call no Strike A (mesmo vencimento e strike).',
    synthetics: 'Equivalente sintético a vender a ação a descoberto com alavancagem.',
    whenToUse: 'Quando você está muito pessimista e deseja replicar a venda da ação com baixo capital.',
    profitProfile: 'Lucro substancial à medida que o mercado cai abaixo do strike A.',
    lossProfile: 'Prejuízo ilimitado caso o mercado suba acima do strike A.',
    timeDecayProfile: 'Neutro.',
    payoffShape: 'line_down',
  },
  {
    id: 5,
    name: 'Venda Coberta de Call (Financiamento)',
    originalName: 'Covered Call / Buy-Write',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar o ativo-objeto à vista e Vender Call no Strike A (ATM ou OTM).',
    whenToUse: 'Geração de renda recorrente sobre carteira de ações e proteção leve contra quedas limitadas.',
    profitProfile: 'Lucro limitado ao prêmio recebido + valorização até o strike A da Call vendida.',
    lossProfile: 'Risco de queda da ação mitigado apenas pelo prêmio da Call recebida.',
    timeDecayProfile: 'Altamente favorável: a passagem do tempo desvaloriza a Call vendida em benefício do investidor.',
    payoffShape: 'trava_alta',
  },
  {
    id: 6,
    name: 'Venda de Put Coberta por Caixa (Cash-Secured Put)',
    originalName: 'Covered Put / Short Put',
    category: 'Precisão',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Vender Put no Strike A mantendo 100% do capital remunerado em CDI.',
    whenToUse: 'Remuneração de caixa ou compra programada de boas ações com desconto em relação ao mercado.',
    profitProfile: 'Lucro limitado ao prêmio total recebido pela venda da Put.',
    lossProfile: 'Obrigação de comprar a ação no strike A caso o mercado caia abaixo dele.',
    timeDecayProfile: 'Muito favorável: Theta positivo acelerado.',
    payoffShape: 'trava_alta',
  },
  {
    id: 7,
    name: 'Compra Simples de Call (Opção de Compra)',
    originalName: 'Long Call',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Call no Strike A (ATM ou levemente OTM).',
    whenToUse: 'Aposta direcional altista explosiva com risco 100% limitado ao prêmio pago.',
    profitProfile: 'Lucro teoricamente ilimitado à medida que o preço da ação supera o strike A + prêmio pago.',
    lossProfile: 'Risco máximo estritamente limitado ao prêmio pago pela opção.',
    timeDecayProfile: 'Desfavorável: o valor extrínseco da opção decai a cada dia útil (Theta negativo).',
    payoffShape: 'line_up',
  },
  {
    id: 8,
    name: 'Compra Simples de Put (Opção de Venda / Seguro de Carteira)',
    originalName: 'Long Put',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Iniciante',
    legsDescription: 'Comprar Put no Strike A.',
    whenToUse: 'Proteção contra quedas bruscas de mercado (Hedge) ou aposta especulativa de baixa.',
    profitProfile: 'Lucro expressivo caso a ação caia abaixo do Strike A - prêmio pago.',
    lossProfile: 'Risco máximo limitado exclusivamente ao prêmio pago.',
    timeDecayProfile: 'Desfavorável (Theta negativo diário).',
    payoffShape: 'line_down',
  },
  {
    id: 9,
    name: 'Venda a Descoberto de Call (Naked Call)',
    originalName: 'Short Call',
    category: 'Precisão',
    bias: 'BAIXA',
    difficulty: 'Avançado',
    legsDescription: 'Vender Call no Strike A sem ter a ação em custódia.',
    whenToUse: 'Cenário de forte convicção de que o preço NÃO ultrapassará o strike A.',
    profitProfile: 'Lucro limitado ao prêmio da opção.',
    lossProfile: 'Risco teoricamente ilimitado caso a ação dispare.',
    timeDecayProfile: 'Muito favorável.',
    payoffShape: 'line_down',
  },
  {
    id: 10,
    name: 'Venda a Descoberto de Put (Naked Put)',
    originalName: 'Short Put',
    category: 'Precisão',
    bias: 'ALTA',
    difficulty: 'Avançado',
    legsDescription: 'Vender Put no Strike A sem margem de garantia integral em caixa.',
    whenToUse: 'Expectativa de alta moderada ou estabilidade de preços.',
    profitProfile: 'Lucro limitado ao prêmio recebido.',
    lossProfile: 'Prejuízo substancial se a ação desabar até zero.',
    timeDecayProfile: 'Muito favorável.',
    payoffShape: 'trava_alta',
  },
  {
    id: 11,
    name: 'Trava de Alta com Call (Bull Call Spread)',
    originalName: 'Bull Spread (Call / Put)',
    category: 'Direcional',
    bias: 'ALTA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Call no Strike A e Vender Call no Strike B (Strike B > Strike A).',
    whenToUse: 'Alta moderada com controle estrito de risco e custo reduzido em relação à Call a seco.',
    profitProfile: 'Lucro máximo: (Strike B - Strike A) - Débito Pago.',
    lossProfile: 'Risco máximo: Débito líquido pago na montagem.',
    timeDecayProfile: 'Moderado (o tempo ajuda se o preço estiver próximo ou acima de B).',
    payoffShape: 'trava_alta',
  },
  {
    id: 12,
    name: 'Trava de Baixa com Put / Call (Bear Spread)',
    originalName: 'Bear Spread (Put / Call)',
    category: 'Direcional',
    bias: 'BAIXA',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar Put no Strike B e Vender Put no Strike A (Strike B > Strike A) ou Vender Call A e Comprar Call B.',
    whenToUse: 'Baixa moderada com risco e retorno previamente limitados.',
    profitProfile: 'Lucro máximo: (Strike B - Strike A) - Custo.',
    lossProfile: 'Perda máxima limitada ao custo da trava.',
    timeDecayProfile: 'Neutro a favorável conforme a proximidade do strike inferior.',
    payoffShape: 'trava_baixa',
  },
  {
    id: 13,
    name: 'Borboleta Comprada (Long Butterfly Spread)',
    originalName: 'Long Butterfly',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Call A, Vender 2 Calls B e Comprar 1 Call C (distâncias iguais entre strikes).',
    whenToUse: 'Alvo de preço de alta precisão no Strike B com relação risco/retorno extremamente assimétrica.',
    profitProfile: 'Lucro máximo atinge o ápice exatamente no Strike central B.',
    lossProfile: 'Perda limitada ao pequeno débito líquido pago.',
    timeDecayProfile: 'Altamente favorável quando o preço se mantém em torno do strike B.',
    payoffShape: 'borboleta',
  },
  {
    id: 14,
    name: 'Borboleta Vendida (Short Butterfly Spread)',
    originalName: 'Short Butterfly',
    category: 'Precisão',
    bias: 'VOLATILIDADE',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call A, Comprar 2 Calls B e Vender 1 Call C.',
    whenToUse: 'Expectativa de rompimento violento para qualquer um dos lados fora do strike central B.',
    profitProfile: 'Lucro obtido se a ação mover-se fortemente para longe de B.',
    lossProfile: 'Perda máxima ocorre caso o mercado expire exatamente no miolo B.',
    timeDecayProfile: 'Desfavorável se o preço ficar parado.',
    payoffShape: 'borboleta',
  },
  {
    id: 15,
    name: 'Condor Comprado (Long Condor)',
    originalName: 'Long Condor',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Call A, Vender 1 Call B, Vender 1 Call C, Comprar 1 Call D.',
    whenToUse: 'Lucrar em faixa mais ampla de estabilidade de preços do que a Borboleta.',
    profitProfile: 'Lucro constante em todo o platô entre os strikes centrais B e C.',
    lossProfile: 'Perda limitada ao débito pago.',
    timeDecayProfile: 'Favorável dentro do platô de consolidação.',
    payoffShape: 'borboleta',
  },
  {
    id: 16,
    name: 'Iron Butterfly a Crédito',
    originalName: 'Short Iron Butterfly',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call B, Vender 1 Put B (Straddle vendido no centro) + Comprar 1 Put A e Comprar 1 Call C para travar as asas.',
    whenToUse: 'Coleta expressiva de prêmio com alta volatilidade implícita e expectativa de estabilidade no Strike B.',
    profitProfile: 'Lucro máximo igual ao crédito total recebido.',
    lossProfile: 'Perda máxima limitada à largura da asa menos o crédito recebido.',
    timeDecayProfile: 'Extremamente acelerado a favor do investidor.',
    payoffShape: 'borboleta',
  },
  {
    id: 17,
    name: 'Straddle Comprado (Long Straddle)',
    originalName: 'Long Straddle',
    category: 'Direcional',
    bias: 'VOLATILIDADE',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar 1 Call ATM e Comprar 1 Put ATM no mesmo strike e vencimento.',
    whenToUse: 'Expectativa de movimento explosivo (Earnings, decisões judiciais, balanços) sem direção definida.',
    profitProfile: 'Lucro ilimitado se o preço andar muito para qualquer um dos lados.',
    lossProfile: 'Perda de 100% dos prêmios pagos caso o ativo fique imóvel.',
    timeDecayProfile: 'Muito agressivo contra a posição (Theta duplo negativo).',
    payoffShape: 'straddle_v',
  },
  {
    id: 18,
    name: 'Straddle Vendido (Short Straddle)',
    originalName: 'Short Straddle',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call ATM e Vender 1 Put ATM.',
    whenToUse: 'Volatilidade implícita extrema e certeza de consolidação do preço.',
    profitProfile: 'Lucro máximo igual ao total dos dois prêmios recebidos.',
    lossProfile: 'Risco ilimitado para ambos os lados.',
    timeDecayProfile: 'Theta duplo positivo máximo.',
    payoffShape: 'straddle_inv',
  },
  {
    id: 19,
    name: 'Strangle Comprado (Long Strangle)',
    originalName: 'Long Strangle',
    category: 'Direcional',
    bias: 'VOLATILIDADE',
    difficulty: 'Intermediário',
    legsDescription: 'Comprar 1 Put OTM (Strike A) e Comprar 1 Call OTM (Strike B).',
    whenToUse: 'Aposta em grande volatilidade com custo de montagem mais barato do que o Straddle.',
    profitProfile: 'Lucro ilimitado após superar os pontos de break-even superior ou inferior.',
    lossProfile: 'Perda limitada ao débito pago.',
    timeDecayProfile: 'Desfavorável.',
    payoffShape: 'strangle_u',
  },
  {
    id: 20,
    name: 'Iron Condor a Crédito (Short Iron Condor)',
    originalName: 'Short Iron Condor / Covered Strangle',
    category: 'Precisão',
    bias: 'LATERAL',
    difficulty: 'Intermediário',
    legsDescription: 'Vender Put B e Comprar Put A (Bull Put Spread) + Vender Call C e Comprar Call D (Bear Call Spread).',
    whenToUse: 'Estratégia rainha da renda com opções: lucrar com a passagem do tempo enquanto a ação oscilar dentro do túnel [Strike B, Strike C].',
    profitProfile: 'Lucro máximo: Crédito líquido total recebido na montagem.',
    lossProfile: 'Perda máxima: (Largura da asa - Crédito recebido) * 1.000 por lote.',
    timeDecayProfile: 'Theta altamente positivo todos os dias úteis.',
    payoffShape: 'strangle_inv',
  },
  {
    id: 21,
    name: 'Ratio Call Spread (Trava de Proporção com Call)',
    originalName: 'Ratio Call Spread',
    category: 'Precisão',
    bias: 'ALTA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Call no Strike A e Vender 2 Calls no Strike B.',
    whenToUse: 'Mercado com alta moderada até o strike B com custo de montagem zero ou crédito.',
    profitProfile: 'Lucro máximo concentrado no strike B.',
    lossProfile: 'Risco ilimitado se o preço disparar acima do segundo break-even.',
    timeDecayProfile: 'Favorável próximo ao strike B.',
    payoffShape: 'trava_alta',
  },
  {
    id: 22,
    name: 'Ratio Put Spread (Trava de Proporção com Put)',
    originalName: 'Ratio Put Spread',
    category: 'Precisão',
    bias: 'BAIXA',
    difficulty: 'Avançado',
    legsDescription: 'Comprar 1 Put no Strike B e Vender 2 Puts no Strike A.',
    whenToUse: 'Mercado com queda moderada até o strike A com custo nulo.',
    profitProfile: 'Lucro máximo no strike A.',
    lossProfile: 'Risco alto caso o ativo desabe expressivamente abaixo do break-even inferior.',
    timeDecayProfile: 'Favorável perto de A.',
    payoffShape: 'trava_baixa',
  },
  {
    id: 23,
    name: 'Backspread de Compra com Call (Call Volatility Backspread)',
    originalName: 'Call Backspread',
    category: 'Direcional',
    bias: 'VOLATILIDADE',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Call A e Comprar 2 Calls B (Strike B > Strike A).',
    whenToUse: 'Expectativa de alta explosiva com proteção contra quedas acentuadas.',
    profitProfile: 'Lucro ilimitado na alta forte.',
    lossProfile: 'Perda máxima concentrada exatamente no Strike B.',
    timeDecayProfile: 'Desfavorável se o preço ficar estagnado.',
    payoffShape: 'backspread_up',
  },
  {
    id: 24,
    name: 'Backspread de Compra com Put (Put Volatility Backspread)',
    originalName: 'Put Backspread',
    category: 'Direcional',
    bias: 'VOLATILIDADE',
    difficulty: 'Avançado',
    legsDescription: 'Vender 1 Put B e Comprar 2 Puts A (Strike B > Strike A).',
    whenToUse: 'Expectativa de crash ou queda profunda do mercado.',
    profitProfile: 'Lucro acelerado na queda acentuada.',
    lossProfile: 'Perda máxima no Strike A.',
    timeDecayProfile: 'Desfavorável na estabilidade.',
    payoffShape: 'backspread_down',
  },
  {
    id: 25,
    name: 'Caixa de Quatro Pontas (Box Spread de Arbitragem)',
    originalName: 'Box Spread (Arbitrage)',
    category: 'Arbitragem',
    bias: 'NEUTRO',
    difficulty: 'Avançado',
    legsDescription: 'Comprar Trava de Alta (Call A + Call B) e Comprar Trava de Baixa (Put B + Put A).',
    whenToUse: 'Operação sintética 100% travada usada para capturar distorções de taxa de juros ou fechar posições.',
    profitProfile: 'O valor no vencimento é exatamente constante (Strike B - Strike A) independente do preço do ativo.',
    lossProfile: 'Risco nulo no vencimento (retorno de renda fixa sintética).',
    timeDecayProfile: 'Neutro.',
    payoffShape: 'box',
  },
];

export const CME_25_STRATEGIES = OPTION_25_STRATEGIES;

/**
 * Seleciona a estratégia de opções ideal com base no Veredito CNPI e nas condições técnicas
 */
export function getRecommendedOptionStrategy(
  verdict: string,
  rsi: number | null,
  trend: string
): OptionStrategySpec {
  if (verdict.includes('COMPRA') || trend === 'ALTA') {
    if (rsi && rsi > 65) {
      // Mercado esticado em alta -> Bull Spread (Trava de alta com risco limitado)
      return OPTION_25_STRATEGIES[10]; // Bull Spread (#11)
    }
    return OPTION_25_STRATEGIES[10]; // Bull Spread (#11) ou Long Call (#7)
  }

  if (verdict.includes('VENDA') || trend === 'BAIXA') {
    return OPTION_25_STRATEGIES[11]; // Bear Spread (#12)
  }

  // Mercado Lateral / Consolidação
  return OPTION_25_STRATEGIES[15]; // Short Iron Butterfly (#16) ou Long Butterfly (#13)
}

export const getRecommendedCMEStrategy = getRecommendedOptionStrategy;
